name: Update Google Sheet

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # каждый день в 03:00 UTC

jobs:
  push-to-sheet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          pip install \
            gspread \
            oauth2client \
            gspread-dataframe \
            pandas

      - name: Run update script
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: python update_tutors.py
